Client/Client/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult IndexAbout()
        {
            return View();
        }
    }
}

Client/Client/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
	public class ContactController : Controller
	{
		public IActionResult IndexContact()
		{
			return View();
		}
	}
}

Client/Client/Controllers/HeaderController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;

namespace Client.Controllers
{
    public class HeaderController : Controller
    {
        private readonly ePRJContext _context;
        public HeaderController(ePRJContext context)
        {
            _context = context;
        }
        public IActionResult _Header1()
        {
            List<Category> c = _context.Categorys.ToList();
            /*List<Category> IsCategory = new List<Category>();
            var danhmuc1 = _context.Categorys.ToList();*/
            return View(c);
            /*ViewBag.Category = danhmuc1;
            return View();*/
            

        }
        
    }
}

Client/Client/Controllers/LoginController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Client.Controllers
{
    public class LoginController : Controller
    {
        ePRJContext _context;
        public LoginController(ePRJContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Customers!.SingleOrDefaultAsync(u => u.UserName == username && u.PassWord == password);
                var u = username;
                if (user != null)
                {
                    var checkActive = await _context.Customers!.SingleOrDefaultAsync(u => u.UserName == username && u.PassWord == password && u.Active == 1);
                    if (checkActive != null)
                    {
                        var session = HttpContext.Session;
                        session.SetInt32("CustomerId", user.Id);
                        session.SetString("Username", user.UserName);
                        session.SetString("FullName", user.FullName);
                        session.SetString("Email", user.Email);
                        session.SetString("PhoneNumber", user.PhoneNumber);
                        session.SetString("Address", user.UserAddress);
                        TempData["message_login_success"] = "Login successful!";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["message_login"] = "Your account is locked!";
                        return RedirectToAction("Index");
                    }
                }

            }
            TempData["message_login"] = "Account not found!";
            return RedirectToAction("Index");
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(Customer data)
        {
            var email = await _context.Customers!.SingleOrDefaultAsync(u => u.Email.Equals(data.Email));
            if (email != null)
            {
                TempData["message_register"] = "Email already exists!";
                return RedirectToAction("Register");
            }
            var tel = await _context.Customers!.SingleOrDefaultAsync(u => u.PhoneNumber.Equals(data.PhoneNumber));
            if (tel != null)
            {
                TempData["message_register"] = "Contact number already exists!";
                return RedirectToAction("Register");
            }
            var username = await _context.Customers!.SingleOrDefaultAsync(u => u.UserName.Equals(data.UserName));
            if (username != null)
            {
                TempData["message_register"] = "Username already exists!";
                return RedirectToAction("Register");
            }
            if (ModelState.IsValid)
            {
                data.PassWord = data.PassWord;
                data.Active = 1;
                _context.Customers!.Add(data);
                await _context.SaveChangesAsync();


                await _context.SaveChangesAsync();

                TempData["message2"] = "Registration successful!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

    }
}

Client/Client/Views/Shared/_Footer.cshtml
<section id="footer" class="clearfix">
	<div class="container">
		<div class="row">
			<div class="footer_1 clearfix">
				<div class="col-sm-3">
					<div class="footer_1l clearfix">
						<h1 class="mgt">
							<a style="font-size:20px" class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-wrench"></i> <span class="col_1">Auto</span> Ancilaries Limited</a>
						</h1>
						<p>Hit the road with the astounding Auto Ancilaries Limited theme, made especially for repair shops, car rental and automotive easing services.</p>
						<div class="footer_1li cleafix">
							<span class="col_1"><i class="fa fa-headphones"></i></span>
							<h5>Customer Support</h5>
							<h4>(84) 355 854 104</h4>
						</div>
					</div>
				</div>
				<div class="col-sm-5">
					<div class="footer_1m clearfix">
						<h4>Subscribe Newsletter To Get Updated</h4><br>
						<div class="header_1m clearfix">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Search">
								<span class="input-group-btn">
									<button class="btn btn-primary" type="button">
										Subscribe
									</button>
								</span>
							</div>
						</div>
						<p>We are a team of designers and developers that create high quality Magento, Prestashop, Opencart...</p>
						<ul class="social-network social-circle">
							<li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
							<li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="footer_1r clearfix">
						<h4>Information</h4>
						<ul>
							<li><a asp-action="Index" asp-controller="Home">Home</a></li>
							<li><a asp-action="IndexProduct" asp-controller="Product">Product</a></li>
							<li><a asp-action="IndexAbout" asp-controller="About">About Us</a></li>
							<li><a asp-action="IndexContact" asp-controller="Contact">Contact Us</a></li>
							
						</ul>
					</div>
				</div>
			</div>
			<div class="footer_2 text-center clearfix">
				<div class="col-sm-12">
					<p class="mgt">© 2023 Your Website Name. All Rights Reserved | Design by <a class="col_1" href="">Auto Ancilaries Limited Team</a></p>
				</div>
			</div>
		</div>
	</div>
</section>

Client/Client/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<style>
    .m_tag1 > a {
        color: white !important;
        font-weight: bold !important;
    }

    .m_tag {
        line-height: 35px
    }

    li {
        height: 70px !important
    }

</style>
<section id="menu" class="clearfix cd-secondary-nav">
    <nav class="navbar nav_t">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-wrench"></i> <span class="col_1">Auto</span> Ancilaries Limited</a>
            </div>

            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li class="m_tag @(ViewContext.RouteData.Values["Action"].ToString()=="Index"?"active_tab":"")">
                        <span class="m_tag1">@Html.ActionLink("Home", "Index", "Home", new {}, new { })</span>
                    </li>
                    <li class="m_tag @(ViewContext.RouteData.Values["Action"].ToString()=="IndexProduct"?"active_tab":"")">
                        <span class="m_tag1">@Html.ActionLink("Product", "IndexProduct", "Product", new {}, new { })</span>
                    </li>

                    @*<li><a class="m_tag" asp-controller="Product" asp-action="Category">Category</a></li>
                    <li class="dropdown">
                    <a class="m_tag" href="#" data-toggle="dropdown" role="button" aria-expanded="false">Category<span class="caret"></span></a>
                    <ul class="dropdown-menu drop_3" role="menu">*@
                    @*@if (Model != null)
                    {
                    @foreach (var item1 in Model)
                    {
                    <li><a asp-action="Category" asp-route-Id="@item1.Id" asp-controller="Product">@item1.Name</a></li>
                    }
                    }*@

                    <li class="m_tag @(ViewContext.RouteData.Values["Action"].ToString()=="IndexAbout"?"active_tab":"")">
                        <span class="m_tag1">@Html.ActionLink("About", "IndexAbout", "About", new {}, new { })</span>
                    </li>

                    <li class="m_tag @(ViewContext.RouteData.Values["Action"].ToString()=="IndexContact"?"active_tab":"")">
                        <span class="m_tag1">@Html.ActionLink("Contact", "IndexContact", "Contact", new {}, new { })</span>
                    </li>




                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

</section>

<section id="header">
    <div class="container">
        <div class="row">
            <div class="header_1 clearfix">
                <div class="col-sm-3">
                    <div class="header_1l clearfix">
                        <h3 class="mgt"><a asp-controller="Home" asp-action="Index"><span class="col_1">Auto</span> Ancilaries Limited</a></h3>

                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="header_1m clearfix">
                        <form asp-action="FindProduct" asp-controller="Search" method="get">
                            <div class="input-group">

                                <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Search">

                                <span class="input-group-btn">
                                    <input class="btn btn-primary" type="submit" value="SEARCH" />
                                    @*<button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                    </button>*@
                                </span>
                                @*<div id="records_table" class="results-box">
                                </div>*@
                            </div>
                        </form>
                    </div>
                </div>
                <div class="header_1r clearfix">
                    <ul class="nav navbar-nav mgt navbar-right">
                        @*                        <li><a asp-controller="Wishlist" asp-action="Index" class="tag_m1"><i class="fa fa-heart-o"></i></a></li>
                        *@
                        <li class="dropdown">
                            <a class="tag_m1" href="/Order" ><i class="glyphicon glyphicon-shopping-cart"></i></a>


                        </li>

                        @{
                            var check = HttpContextAccessor.HttpContext.Session.GetString("Username");

                            @if (check != null)
                            {
                                <li>
                                    <a class="tag_m1" asp-action="logout" asp-controller="Login"><i class="fa fa-sign-out"></i></a>
                                </li>
                            }
                            else
                            {
                                <li><a class="tag_m1" asp-controller="Login" asp-action="Index"><i class="fa fa-user"></i></a></li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

Client/Client/Views/Shared/_Header1.cshtml
@model IEnumerable<Client.Models.Category>;
@*@{
    Category category = ViewBag.CurrentCat;
}*@

<section id="menu" class="clearfix cd-secondary-nav">
    <nav class="navbar nav_t">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-wrench"></i> <span class="col_1">Auto</span> Ancilaries Limited</a>
            </div>

            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li><a class="m_tag active_tab" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="m_tag" asp-controller="Product" asp-action="IndexProduct">Product</a></li>

                    @*<li><a class="m_tag" asp-controller="Product" asp-action="Category">Category</a></li>*@
                    <li class="dropdown">
                        <a class="m_tag" href="#" data-toggle="dropdown" role="button" aria-expanded="false">Category<span class="caret"></span></a>
                        <ul class="dropdown-menu drop_3" role="menu">
                            
                            @if(Model != null)
                            {
                                @foreach (var item in Model)
                                {
                                    <li><h5><a asp-action="Category" asp-route-Id="@item.Id" asp-controller="Product">@Html.DisplayFor(m=>item.Name)</a></h5></li>
                                }
                            }
                        </ul>
                    </li>
                    
                    <li><a class="m_tag" asp-controller="About" asp-action="IndexAbout">About Us</a></li>

                    <li><a class="m_tag" asp-controller="Contact" asp-action="IndexContact">Contact</a></li>




                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

</section>

<section id="header">
    <div class="container">
        <div class="row">
            <div class="header_1 clearfix">
                <div class="col-sm-3">
                    <div class="header_1l clearfix">
                        <h3 class="mgt"><a asp-controller="Home" asp-action="Index"><span class="col_1">Auto</span> Ancilaries Limited</a></h3>

                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="header_1m clearfix">
                        <form asp-action="FindProduct" asp-controller="Search" method="get">
                            <div class="input-group">

                                <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Search">

                                <span class="input-group-btn">
                                    <input class="btn btn-primary" type="submit" value="SEARCH" />
                                    @*<button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                    </button>*@
                                </span>
                                @*<div id="records_table" class="results-box">
                                </div>*@
                            </div>
                        </form>
                    </div>
                </div>
                <div class="header_1r clearfix">
                    <ul class="nav navbar-nav mgt navbar-right">
                        <li><a asp-controller="Wishlist" asp-action="Index" class="tag_m1"><i class="fa fa-heart-o"></i></a></li>
                        <li><a class="tag_m1" asp-controller="Login" asp-action="Index"><i class="fa fa-user"></i></a></li>
                        <li class="dropdown">
                            <a class="tag_m1" href="#" data-toggle="dropdown" role="button" aria-expanded="false"><i class="glyphicon glyphicon-shopping-cart"></i></a>
                            <ul class="dropdown-menu drop_1" role="menu">
                                <li>
                                    <div class="drop_1i clearfix">
                                        <div class="col-sm-6">
                                            <div class="drop_1il clearfix"><h5 class="mgt">2 ITEMS</h5></div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="drop_1il text-right clearfix"><h5 class="mgt"><a href="#">VIEW CART</a></h5></div>
                                        </div>
                                    </div>
                                    <div class="drop_1i1 clearfix">
                                        <div class="col-sm-8">
                                            <div class="drop_1i1l clearfix"><h6 class="mgt bold"><a href="#">Nulla Quis</a> <br> <span class="normal col_2">1x - $89.00</span> <br> <span><i class="fa fa-remove"></i></span></h6></div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="drop_1i1r text-right clearfix"><a href="#"><img src="~/Assets/User/Home/css/1.jpg" class="iw" alt="abc"></a></div>
                                        </div>
                                    </div>
                                    <div class="drop_1i1 clearfix">
                                        <div class="col-sm-8">
                                            <div class="drop_1i1l clearfix"><h6 class="mgt bold"><a href="#">Eget Nulla</a> <br> <span class="normal col_2">1x - $49.00</span> <br> <span><i class="fa fa-remove"></i></span></h6></div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="drop_1i1r text-right clearfix"><a href="#"><img src="~/Assets/User/Home/css/2.png" class="iw" alt="abc"></a></div>
                                        </div>
                                    </div>
                                    <div class="drop_1i2 clearfix">
                                        <div class="col-sm-6">
                                            <div class="drop_1il clearfix"><h5 class="mgt">TOTAL</h5></div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="drop_1il text-right clearfix"><h5 class="mgt">$138.00</h5></div>
                                        </div>
                                    </div>
                                    <div class="drop_1i3 text-center clearfix">
                                        <div class="col-sm-12">
                                            <h5><a class="button_1 block" href="#">CHECKOUT</a></h5>
                                            <h5><a class="button block" href="#">VIEW CART</a></h5>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

Client/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Auto Ancilaries Limited</title>
	<link href="~/LogoWeb.png" rel="icon">
	<link href="~/Assets/User/Home/css/bootstrap.min.css" rel="stylesheet">
	<link href="~/Assets/User/Home/css/global.css" rel="stylesheet">
	<link href="~/Assets/User/Home/css/index.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="~/Assets/User/Home/css/font-awesome.min.css" />
	<link href="https://fonts.googleapis.com/css2?family=Baloo+2&display=swap" rel="stylesheet">
	<script src="~/Assets/User/Home/js/jquery-2.1.1.min.js"></script>
	<script src="~/Assets/User/Home/js/bootstrap.min.js"></script>
</head>


<body>

	@*Header*@
	@await Html.PartialAsync("_Header.cshtml")
	@*@Html.PartialAsync("~/Views/Shared/_Header.cshtml")*@
	@*@{
		Html.RenderPartial("_Header");
	}*@
	
	@*@Html.Action("_Header", "Home")*@
	@*Header*@
	@RenderBody();
	@*Footer*@
	@await Html.PartialAsync("_Footer.cshtml")
	@*Footer*@
	

	<script>
		$(document).ready(function () {
			/*****Fixed Menu******/
			var secondaryNav = $('.cd-secondary-nav'),
				secondaryNavTopPosition = secondaryNav.offset().top;
			$(window).on('scroll', function () {
				if ($(window).scrollTop() > secondaryNavTopPosition) {
					secondaryNav.addClass('is-fixed');
				} else {
					secondaryNav.removeClass('is-fixed');
				}
			});

		});
	</script>
	@*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>*@
	@await RenderSectionAsync("Scripts", required: false)

</body>

</html>