Client/Client/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Client.Models;
/*using Client.Helpper;*/
using PagedList.Core;
using Grpc.Core;
using Microsoft.Extensions.Hosting;

namespace Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly ePRJContext _context;
        private IWebHostEnvironment _environment;

        public AdminProductsController(ePRJContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Admin/AdminProducts
        public IActionResult Index(int page = 1, int CatID = 0)
        {
            if (HttpContext.Session.GetInt32("IdAdmin") != null)
            {
                var pageNumber = page;
                var pageSize = 8;

                List<Product> IsProducts = new List<Product>();
                if (CatID != 0)
                {
                    IsProducts = _context.Products
                    .AsNoTracking()
                    .Where(x => x.CategoryId == CatID)
                    .Include(x => x.Category)
                    .OrderByDescending(x => x.Id).ToList();
                }
                else
                {
                    IsProducts = _context.Products
                    .AsNoTracking()
                    .Include(x => x.Category)
                    .OrderByDescending(x => x.Id).ToList();
                }

                PagedList<Product> models = new PagedList<Product>(IsProducts.AsQueryable(), pageNumber, pageSize);
                ViewBag.CurrentCateID = CatID;
                ViewBag.CurrentPage = pageNumber;
                ViewData["Categories"] = new SelectList(_context.Categorys, "Id", "Name");
                return View(models);
            }
            return RedirectToAction("Index", "AdminLogin");
        }

        public IActionResult Filter(int CatID = 0)
        {
            var url = $"/Admin/AdminProducts?CatID={CatID}";
            if (CatID == 0)
            {
                url = $"/Admin/AdminProducts";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["Categories"] = new SelectList(_context.Categorys, "Id", "Name");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult?> Create(ProductDto product)
        {
            if (ModelState.IsValid)
            {


                string filename = string.Empty;
                string filename1 = string.Empty;
                string filename2 = string.Empty;
                string filename3 = string.Empty;
                if (product.Avatar != null)
                {
                    filename = product.Avatar.FileName;
                    var imageFolder = Path.Combine(_environment.WebRootPath + "/images");

                    if (!Directory.Exists(imageFolder))
                    {
                        Directory.CreateDirectory(imageFolder);
                    }

                    var filePath = Path.Combine(imageFolder, filename);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await product.Avatar.CopyToAsync(stream);
                }
                if (product.Image1 != null)
                {
                    filename1 = product.Image1.FileName;
                    var imageFolder1 = Path.Combine(_environment.WebRootPath + "/images");

                    if (!Directory.Exists(imageFolder1))
                    {
                        Directory.CreateDirectory(imageFolder1);
                    }

                    var filePath = Path.Combine(imageFolder1, filename1);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await product.Image1.CopyToAsync(stream);
                }
                if (product.Image2 != null)
                {
                    filename2 = product.Image2.FileName;
                    var imageFolder2 = Path.Combine(_environment.WebRootPath + "/images");

                    if (!Directory.Exists(imageFolder2))
                    {
                        Directory.CreateDirectory(imageFolder2);
                    }

                    var filePath = Path.Combine(imageFolder2, filename2);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await product.Image2.CopyToAsync(stream);
                }
                if (product.Image3 != null)
                {
                    filename3 = product.Image3.FileName;
                    var imageFolder3 = Path.Combine(_environment.WebRootPath + "/images");

                    if (!Directory.Exists(imageFolder3))
                    {
                        Directory.CreateDirectory(imageFolder3);
                    }

                    var filePath = Path.Combine(imageFolder3, filename3);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await product.Image3.CopyToAsync(stream);
                }
                var i = new Product { ProductName = product.ProductName, Rate = product.Rate, Price = product.Price, Description = product.Description, Avatar = filename, Image1 = filename1, Image2 = filename2, Image3 = filename3, CategoryId = product.CategoryId, Status = product.Status };
                _context.Products.Add(i);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Categories"] = new SelectList(_context.Categorys, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();

            }


            Product? product = await _context.Products!.FirstOrDefaultAsync(x => x.Id == id!);

            if (product == null)
            {
                return NotFound();
            }

            ProductDto dto = new ProductDto { ProductName = product.ProductName, Rate = product.Rate, Price = product.Price, Description = product.Description, CategoryId = product.CategoryId, Status = product.Status };
            ViewData["Categories"] = new SelectList(_context.Categorys, "Id", "Name", product.CategoryId);
            return View(dto);


        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductDto product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Product? old = await _context.Products!.FirstOrDefaultAsync(x => x.Id == id);
                try
                {
                    string filename = string.Empty;
                    string filename1 = string.Empty;
                    string filename2 = string.Empty;
                    string filename3 = string.Empty;
                    if (product.Avatar != null)
                    {
                        filename = product.Avatar.FileName;
                        var imageFolder = Path.Combine(_environment.WebRootPath + "/images");

                        if (!Directory.Exists(imageFolder))
                        {
                            Directory.CreateDirectory(imageFolder);
                        }

                        var filePath = Path.Combine(imageFolder, filename);
                        var stream = new FileStream(filePath, FileMode.Create);
                        await product.Avatar.CopyToAsync(stream);
                    }
                    if (product.Image1 != null)
                    {
                        filename1 = product.Image1.FileName;
                        var imageFolder1 = Path.Combine(_environment.WebRootPath + "/images");

                        if (!Directory.Exists(imageFolder1))
                        {
                            Directory.CreateDirectory(imageFolder1);
                        }

                        var filePath = Path.Combine(imageFolder1, filename1);
                        var stream = new FileStream(filePath, FileMode.Create);
                        await product.Image1.CopyToAsync(stream);
                    }
                    if (product.Image2 != null)
                    {
                        filename2 = product.Image2.FileName;
                        var imageFolder2 = Path.Combine(_environment.WebRootPath + "/images");

                        if (!Directory.Exists(imageFolder2))
                        {

Client/Client/Areas/Admin/Views/AdminProducts/Create.cshtml
@model Client.Models.ProductDto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .form-control {
        background-color: azure;
    }

    .form-group {
        padding: 10px 0 10px 0;
    }

    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        /* Hide default HTML checkbox */
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #C81313;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #C81313;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }
</style>
<div class="content">
    <div class="container-fluid pt-4 px-4">
        <h3><a asp-action="Create" asp-controller="AdminProducts" class="mb-0">CREATE NEW PRODUCTS</a></h3>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create" asp-controller="AdminProducts" method="post" enctype="multipart/form-data">
                    @*@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {*@
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ProductName" class="control-label"></label>
                        <input asp-for="ProductName" class="form-control" />
                        <span asp-validation-for="ProductName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Rate" class="control-label"></label>
                        <input asp-for="Rate" class="form-control" />
                        <span asp-validation-for="Rate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2"})*@
                        <label asp-for="Avatar" class="control-label"></label>
                        <input asp-for="Avatar" class="form-control" type="file" />
                        <span asp-validation-for="Avatar" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Image1, htmlAttributes: new { @class = "control-label col-md-2"})*@

                        <label asp-for="Image1" class="control-label"></label>
                        <input asp-for="Image1" class="form-control" type="file" />
                        <span asp-validation-for="Image1" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Image2, htmlAttributes: new { @class = "control-label col-md-2"})*@

                        <label asp-for="Image2" class="control-label"></label>
                        <input asp-for="Image2" class="form-control" type="file" />
                        <span asp-validation-for="Image2" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Image3, htmlAttributes: new { @class = "control-label col-md-2"})*@

                        <label asp-for="Image3" class="control-label"></label>
                        <input asp-for="Image3" class="form-control" type="file" />
                        <span asp-validation-for="Image3" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                    </div>
                    @*<div class="form-group">
                    <label asp-for="Status" class="control-label"></label>
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>

                    </div>*@
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="Status" value="true" checked>
                        <label class="form-check-label" for="Status">
                            Active
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="Status" value="false">
                        <label class="form-check-label" for="Status">
                            Unactive
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>

            </div>
        </div>

        <div>
            <a asp-action="IndexProduct">Back to List</a>
        </div>

    </div>
</div>

Client/Client/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model Client.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="container-fluid pt-4 px-4">
        <h3><a asp-action="Delete" asp-controller="AdminProducts" class="mb-0">DELETE PRODUCT</a></h3>
        <hr />
        <h3 class="text-primary">Are you sure you want to delete this?</h3>

        <div>
            <dl class="row">
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductName)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductName)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Rate)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Rate)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Avatar)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Avatar)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image1)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image1)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image2)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image2)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image3)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image3)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @if (Model.Status == true)
                    {
                            <i style="font-size:40px; color:#C81313" class="fa fa-check" aria-hidden="true"></i>
                    }
                    else
                    {

                            <i style="font-size:40px" class="fa fa-times " aria-hidden="true"></i>

                    }
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Category)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Category.Name)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="IndexProduct">Back to List</a>
            </form>
        </div>
    </div>
</div>

Client/Client/Areas/Admin/Views/AdminProducts/Details.cshtml
@model Client.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<style>
   

    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        /* Hide default HTML checkbox */
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #C81313;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #C81313;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }

</style>

<div class="content">
    <div class="container-fluid pt-4 px-4">
        <h3><a asp-action="Details" asp-controller="AdminProducts" class="mb-0">DETAIL PRODUCT</a></h3>
        <hr />
        <div>
            <dl class="row">
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ProductName)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.ProductName)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Rate)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Rate)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Avatar)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Avatar)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image1)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image1)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image2)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image2)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image3)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    <img class="center" src="~/images/@Html.DisplayFor(model => model.Image3)" style="width:150px; height:auto" />
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @if (Model.Status == true)
                    {
                        <i style="font-size:40px; color:#C81313" class="fa fa-check" aria-hidden="true"></i>
                    }
                    else
                    {

                        <i style="font-size:40px" class="fa fa-times " aria-hidden="true"></i>

                    }
                    @*<div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <label class="switch">
                            <input type="checkbox" asp-for="Status">
                            <span class="slider round"></span>

                        </label>
                    </div>*@
                    @*@Html.DisplayFor(model => model.Status)*@
                </dd>
                <dt style="padding: 10px 0 10px 0;" class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Category)
                </dt>
                <dd style="padding: 10px 0 10px 0;" class="col-sm-10">
                    @Html.DisplayFor(model => model.Category.Name)
                </dd>
            </dl>
        </div>
        <div>
            
            <a asp-action="IndexProduct">Back to List</a>
        </div>
    </div>
</div>